FoodTracker/FoodTrackerApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('users/', views.user_list, name='user_list'),
    path('products/', views.product_list, name = 'product_list'),
]

FoodTracker/FoodTrackerApp/models.py
from django.db import models


class User(models.Model):
    username = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    usr_password = models.CharField(max_length=255)
    age = models.IntegerField()
    weight = models.DecimalField(max_digits=5, decimal_places=2)
    height = models.DecimalField(max_digits=5, decimal_places=2)
    sex = models.CharField(max_length=10, choices=[('male', 'Male'), ('female', 'Female')])
    activity_level = models.CharField(max_length=50)
    img_url = models.CharField(max_length=1000)

    class Meta:
        db_table = 'users'


class Frige(models.Model):
    product_id = models.IntegerField()
    user_id = models.IntegerField()
    location = models.CharField(max_length = 100)
    expire_data = models.DateField()
    weight = models.DecimalField(max_digits=5, decimal_places=2)
    how_much = models.DecimalField(max_digits=5, decimal_places=2)
    


class Product(models.Model):
    user_id = models.IntegerField()
    product_name = models.CharField(max_length = 100)
    calories = models.DecimalField(max_digits=5, decimal_places=2)
    protein = models.DecimalField(max_digits=5, decimal_places=2)
    fat = models.DecimalField(max_digits=5, decimal_places=2)
    carbohydrates = models.DecimalField(max_digits=5, decimal_places=2)
    barcode = models.CharField(max_length=1000)
    img_url = models.CharField(max_length=1000)



class Recipe(models.Model):
    user_id = models.IntegerField()
    name = models.CharField(max_length = 100)
    annotation = models.CharField(max_length = 100)
    recepe_text = models.CharField(max_length = 100)
    rate = models.DecimalField(max_digits=5, decimal_places=2)
    img_url = models.CharField(max_length=1000)
    


class RecipesProducts(models.Model):
    product_id = models.IntegerField()
    recipe_id = models.IntegerField()

FoodTracker/FoodTrackerApp/views.py
from django.shortcuts import render

from django.http import HttpResponse
from .models import User, Product


def index(request):
    return HttpResponse("hello test django")



def user_list(request):
    users = User.objects.all()
    return render(request, 'user_list.html', {'users': users})


def product_list(request):
    products = Product.objects.all()
    return render(request, 'products_list.html',{'products' : products})

FoodTracker/FoodTrackerApp/templates/frige_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Список шняг из холодильника/title>
</head>
<body>
    <h1>Список шняг из холодильника</h1>
    <table>
        <thead>
            <tr>
                <th>Имя пользователя</th>
                <th>Электронная почта</th>
                <th>Возраст</th>
                <th>Вес</th>
                <th>Рост</th>
                <th>Пол</th>
                <th>Уровень активности</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.username }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.age }}</td>
                    <td>{{ user.weight }}</td>
                    <td>{{ user.height }}</td>
                    <td>{{ user.get_sex_display }}</td>
                    <td>{{ user.activity_level }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

FoodTracker/FoodTrackerApp/templates/products_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Products list</title>
</head>
<body>
    <h1>Products list</h1>
    <table>
        <thead>
            <tr>
                <th>user id</th>
                <th>product name</th>
                <th>calories</th>
                <th>protein</th>
                <th>fat</th>
                <th>carbohydrates</th>
                <th>barcode</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
                <tr>
                    <td>{{ product.user_id }}</td>
                    <td>{{ product.product_name }}</td>
                    <td>{{ product.calories }}</td>
                    <td>{{ product.protein }}</td>
                    <td>{{ product.fat }}</td>
                    <td>{{ product.carbohydrates }}</td>
                    <td>{{ product.barcode }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

FoodTracker/FoodTrackerApp/templates/user_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Список пользователей</title>
</head>
<body>
    <h1>Список пользователей</h1>
    <table>
        <thead>
            <tr>
                <th>Имя пользователя</th>
                <th>Электронная почта</th>
                <th>Возраст</th>
                <th>Вес</th>
                <th>Рост</th>
                <th>Пол</th>
                <th>Уровень активности</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.username }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.age }}</td>
                    <td>{{ user.weight }}</td>
                    <td>{{ user.height }}</td>
                    <td>{{ user.get_sex_display }}</td>
                    <td>{{ user.activity_level }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>